/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca.telas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import sistemabiblioteca.controladores.Controlador;

/**
 *
 * @author Indiara
 */
public class TelaInicial extends javax.swing.JFrame {

    private Controlador controlador;
    public GerenciadorEventos gerenciador;
    public TelaInicial(Controlador ctrl) {
        this.gerenciador = new GerenciadorEventos();
        this.controlador=ctrl;
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelGeral = new javax.swing.JPanel();
        emprestimo = new javax.swing.JButton();
        devolucao = new javax.swing.JButton();
        consulta = new javax.swing.JButton();
        painelAdm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        livros = new javax.swing.JButton();
        clientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("false"), this, org.jdesktop.beansbinding.BeanProperty.create("resizable"));
        bindingGroup.addBinding(binding);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Gerenciamento de Bibliotecas");

        emprestimo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        emprestimo.setActionCommand(emprestimo.getText());
        emprestimo.setText("Empréstimo");
        emprestimo.addActionListener((ActionListener) gerenciador);
        emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimoActionPerformed(evt);
            }
        });

        devolucao.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        devolucao.setText("Devolução");
        devolucao.setActionCommand(devolucao.getText());
        devolucao.addActionListener((ActionListener) gerenciador);

        consulta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        consulta.setText("Consultar");
        consulta.setActionCommand(consulta.getText());
        consulta.addActionListener((ActionListener) gerenciador);

        devolucao.setActionCommand(devolucao.getText());
        devolucao.addActionListener((ActionListener) gerenciador);

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addComponent(emprestimo)
                .addGap(28, 28, 28)
                .addComponent(devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emprestimo)
                    .addComponent(devolucao)
                    .addComponent(consulta))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Area exclusiva para Administração");

        livros.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        livros.setText("Gerenciar livros");
        livros.addActionListener((ActionListener) gerenciador);

        clientes.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        clientes.setText("Gerenciar clientes");
        clientes.addActionListener((ActionListener) gerenciador);

        javax.swing.GroupLayout painelAdmLayout = new javax.swing.GroupLayout(painelAdm);
        painelAdm.setLayout(painelAdmLayout);
        painelAdmLayout.setHorizontalGroup(
            painelAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(painelAdmLayout.createSequentialGroup()
                        .addComponent(livros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clientes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAdmLayout.setVerticalGroup(
            painelAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(livros)
                    .addComponent(clientes))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(painelAdm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(painelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientes;
    private javax.swing.JButton consulta;
    private javax.swing.JButton devolucao;
    private javax.swing.JButton emprestimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton livros;
    private javax.swing.JPanel painelAdm;
    private javax.swing.JPanel painelGeral;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables



public class GerenciadorEventos implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent event) {
            if(event.getActionCommand().equals(emprestimo.getActionCommand())){
                controlador.setTelaEmprestimo();
            }else if(event.getActionCommand().equals(clientes.getActionCommand())){
                controlador.setTelaClientes();
            }else if(event.getActionCommand().equals(devolucao.getActionCommand())){
                controlador.setTelaDevolucao();
            }else if(event.getActionCommand().equals(livros.getActionCommand())){
                controlador.getTelaLivros().getCodigotf().setText(controlador.geradorCodigo());
                controlador.setTelaLivros();
            }else if(event.getActionCommand().equals(consulta.getActionCommand())){
                controlador.setTelaBusca();
            }
        }
    
}
}
